// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v3.21.12
// source: servicios.proto

package serviciosCancion

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PeticionDTO struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Titulo        string                 `protobuf:"bytes,1,opt,name=titulo,proto3" json:"titulo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PeticionDTO) Reset() {
	*x = PeticionDTO{}
	mi := &file_servicios_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeticionDTO) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeticionDTO) ProtoMessage() {}

func (x *PeticionDTO) ProtoReflect() protoreflect.Message {
	mi := &file_servicios_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeticionDTO.ProtoReflect.Descriptor instead.
func (*PeticionDTO) Descriptor() ([]byte, []int) {
	return file_servicios_proto_rawDescGZIP(), []int{0}
}

func (x *PeticionDTO) GetTitulo() string {
	if x != nil {
		return x.Titulo
	}
	return ""
}

type PeticionGeneroDTO struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Genero        string                 `protobuf:"bytes,1,opt,name=genero,proto3" json:"genero,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PeticionGeneroDTO) Reset() {
	*x = PeticionGeneroDTO{}
	mi := &file_servicios_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeticionGeneroDTO) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeticionGeneroDTO) ProtoMessage() {}

func (x *PeticionGeneroDTO) ProtoReflect() protoreflect.Message {
	mi := &file_servicios_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeticionGeneroDTO.ProtoReflect.Descriptor instead.
func (*PeticionGeneroDTO) Descriptor() ([]byte, []int) {
	return file_servicios_proto_rawDescGZIP(), []int{1}
}

func (x *PeticionGeneroDTO) GetGenero() string {
	if x != nil {
		return x.Genero
	}
	return ""
}

type Genero struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Nombre        string                 `protobuf:"bytes,2,opt,name=Nombre,proto3" json:"Nombre,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Genero) Reset() {
	*x = Genero{}
	mi := &file_servicios_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Genero) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Genero) ProtoMessage() {}

func (x *Genero) ProtoReflect() protoreflect.Message {
	mi := &file_servicios_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Genero.ProtoReflect.Descriptor instead.
func (*Genero) Descriptor() ([]byte, []int) {
	return file_servicios_proto_rawDescGZIP(), []int{2}
}

func (x *Genero) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Genero) GetNombre() string {
	if x != nil {
		return x.Nombre
	}
	return ""
}

type Cancion struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Titulo        string                 `protobuf:"bytes,2,opt,name=Titulo,proto3" json:"Titulo,omitempty"`
	Artista_Banda string                 `protobuf:"bytes,3,opt,name=Artista_Banda,json=ArtistaBanda,proto3" json:"Artista_Banda,omitempty"`
	Lanzamiento   int32                  `protobuf:"varint,4,opt,name=Lanzamiento,proto3" json:"Lanzamiento,omitempty"`
	Duracion      string                 `protobuf:"bytes,5,opt,name=Duracion,proto3" json:"Duracion,omitempty"`
	ObjGenero     *Genero                `protobuf:"bytes,6,opt,name=objGenero,proto3" json:"objGenero,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Cancion) Reset() {
	*x = Cancion{}
	mi := &file_servicios_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Cancion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cancion) ProtoMessage() {}

func (x *Cancion) ProtoReflect() protoreflect.Message {
	mi := &file_servicios_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cancion.ProtoReflect.Descriptor instead.
func (*Cancion) Descriptor() ([]byte, []int) {
	return file_servicios_proto_rawDescGZIP(), []int{3}
}

func (x *Cancion) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Cancion) GetTitulo() string {
	if x != nil {
		return x.Titulo
	}
	return ""
}

func (x *Cancion) GetArtista_Banda() string {
	if x != nil {
		return x.Artista_Banda
	}
	return ""
}

func (x *Cancion) GetLanzamiento() int32 {
	if x != nil {
		return x.Lanzamiento
	}
	return 0
}

func (x *Cancion) GetDuracion() string {
	if x != nil {
		return x.Duracion
	}
	return ""
}

func (x *Cancion) GetObjGenero() *Genero {
	if x != nil {
		return x.ObjGenero
	}
	return nil
}

type RespuestaCancionDTO struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mensaje       string                 `protobuf:"bytes,1,opt,name=mensaje,proto3" json:"mensaje,omitempty"`
	Codigo        int32                  `protobuf:"varint,2,opt,name=codigo,proto3" json:"codigo,omitempty"`
	ObjCancion    *Cancion               `protobuf:"bytes,3,opt,name=objCancion,proto3" json:"objCancion,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RespuestaCancionDTO) Reset() {
	*x = RespuestaCancionDTO{}
	mi := &file_servicios_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RespuestaCancionDTO) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RespuestaCancionDTO) ProtoMessage() {}

func (x *RespuestaCancionDTO) ProtoReflect() protoreflect.Message {
	mi := &file_servicios_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RespuestaCancionDTO.ProtoReflect.Descriptor instead.
func (*RespuestaCancionDTO) Descriptor() ([]byte, []int) {
	return file_servicios_proto_rawDescGZIP(), []int{4}
}

func (x *RespuestaCancionDTO) GetMensaje() string {
	if x != nil {
		return x.Mensaje
	}
	return ""
}

func (x *RespuestaCancionDTO) GetCodigo() int32 {
	if x != nil {
		return x.Codigo
	}
	return 0
}

func (x *RespuestaCancionDTO) GetObjCancion() *Cancion {
	if x != nil {
		return x.ObjCancion
	}
	return nil
}

// Respuesta para múltiples canciones
type RespuestaListaCancionesDTO struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mensaje       string                 `protobuf:"bytes,1,opt,name=mensaje,proto3" json:"mensaje,omitempty"`
	Codigo        int32                  `protobuf:"varint,2,opt,name=codigo,proto3" json:"codigo,omitempty"`
	Canciones     []*Cancion             `protobuf:"bytes,3,rep,name=canciones,proto3" json:"canciones,omitempty"` // ¡Aquí está el array!
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RespuestaListaCancionesDTO) Reset() {
	*x = RespuestaListaCancionesDTO{}
	mi := &file_servicios_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RespuestaListaCancionesDTO) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RespuestaListaCancionesDTO) ProtoMessage() {}

func (x *RespuestaListaCancionesDTO) ProtoReflect() protoreflect.Message {
	mi := &file_servicios_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RespuestaListaCancionesDTO.ProtoReflect.Descriptor instead.
func (*RespuestaListaCancionesDTO) Descriptor() ([]byte, []int) {
	return file_servicios_proto_rawDescGZIP(), []int{5}
}

func (x *RespuestaListaCancionesDTO) GetMensaje() string {
	if x != nil {
		return x.Mensaje
	}
	return ""
}

func (x *RespuestaListaCancionesDTO) GetCodigo() int32 {
	if x != nil {
		return x.Codigo
	}
	return 0
}

func (x *RespuestaListaCancionesDTO) GetCanciones() []*Cancion {
	if x != nil {
		return x.Canciones
	}
	return nil
}

var File_servicios_proto protoreflect.FileDescriptor

const file_servicios_proto_rawDesc = "" +
	"\n" +
	"\x0fservicios.proto\x12\x13capaFachadaServices\"%\n" +
	"\vPeticionDTO\x12\x16\n" +
	"\x06titulo\x18\x01 \x01(\tR\x06titulo\"+\n" +
	"\x11PeticionGeneroDTO\x12\x16\n" +
	"\x06genero\x18\x01 \x01(\tR\x06genero\"0\n" +
	"\x06Genero\x12\x0e\n" +
	"\x02Id\x18\x01 \x01(\x05R\x02Id\x12\x16\n" +
	"\x06Nombre\x18\x02 \x01(\tR\x06Nombre\"\xcf\x01\n" +
	"\aCancion\x12\x0e\n" +
	"\x02Id\x18\x01 \x01(\x05R\x02Id\x12\x16\n" +
	"\x06Titulo\x18\x02 \x01(\tR\x06Titulo\x12#\n" +
	"\rArtista_Banda\x18\x03 \x01(\tR\fArtistaBanda\x12 \n" +
	"\vLanzamiento\x18\x04 \x01(\x05R\vLanzamiento\x12\x1a\n" +
	"\bDuracion\x18\x05 \x01(\tR\bDuracion\x129\n" +
	"\tobjGenero\x18\x06 \x01(\v2\x1b.capaFachadaServices.GeneroR\tobjGenero\"\x85\x01\n" +
	"\x13RespuestaCancionDTO\x12\x18\n" +
	"\amensaje\x18\x01 \x01(\tR\amensaje\x12\x16\n" +
	"\x06codigo\x18\x02 \x01(\x05R\x06codigo\x12<\n" +
	"\n" +
	"objCancion\x18\x03 \x01(\v2\x1c.capaFachadaServices.CancionR\n" +
	"objCancion\"\x8a\x01\n" +
	"\x1aRespuestaListaCancionesDTO\x12\x18\n" +
	"\amensaje\x18\x01 \x01(\tR\amensaje\x12\x16\n" +
	"\x06codigo\x18\x02 \x01(\x05R\x06codigo\x12:\n" +
	"\tcanciones\x18\x03 \x03(\v2\x1c.capaFachadaServices.CancionR\tcanciones2\xdd\x01\n" +
	"\x12serviciosCanciones\x12[\n" +
	"\rBuscarCancion\x12 .capaFachadaServices.PeticionDTO\x1a(.capaFachadaServices.RespuestaCancionDTO\x12j\n" +
	"\x0fBuscarPorGenero\x12&.capaFachadaServices.PeticionGeneroDTO\x1a/.capaFachadaServices.RespuestaListaCancionesDTOB\x13Z\x11/serviciosCancionb\x06proto3"

var (
	file_servicios_proto_rawDescOnce sync.Once
	file_servicios_proto_rawDescData []byte
)

func file_servicios_proto_rawDescGZIP() []byte {
	file_servicios_proto_rawDescOnce.Do(func() {
		file_servicios_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_servicios_proto_rawDesc), len(file_servicios_proto_rawDesc)))
	})
	return file_servicios_proto_rawDescData
}

var file_servicios_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_servicios_proto_goTypes = []any{
	(*PeticionDTO)(nil),                // 0: capaFachadaServices.PeticionDTO
	(*PeticionGeneroDTO)(nil),          // 1: capaFachadaServices.PeticionGeneroDTO
	(*Genero)(nil),                     // 2: capaFachadaServices.Genero
	(*Cancion)(nil),                    // 3: capaFachadaServices.Cancion
	(*RespuestaCancionDTO)(nil),        // 4: capaFachadaServices.RespuestaCancionDTO
	(*RespuestaListaCancionesDTO)(nil), // 5: capaFachadaServices.RespuestaListaCancionesDTO
}
var file_servicios_proto_depIdxs = []int32{
	2, // 0: capaFachadaServices.Cancion.objGenero:type_name -> capaFachadaServices.Genero
	3, // 1: capaFachadaServices.RespuestaCancionDTO.objCancion:type_name -> capaFachadaServices.Cancion
	3, // 2: capaFachadaServices.RespuestaListaCancionesDTO.canciones:type_name -> capaFachadaServices.Cancion
	0, // 3: capaFachadaServices.serviciosCanciones.BuscarCancion:input_type -> capaFachadaServices.PeticionDTO
	1, // 4: capaFachadaServices.serviciosCanciones.BuscarPorGenero:input_type -> capaFachadaServices.PeticionGeneroDTO
	4, // 5: capaFachadaServices.serviciosCanciones.BuscarCancion:output_type -> capaFachadaServices.RespuestaCancionDTO
	5, // 6: capaFachadaServices.serviciosCanciones.BuscarPorGenero:output_type -> capaFachadaServices.RespuestaListaCancionesDTO
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_servicios_proto_init() }
func file_servicios_proto_init() {
	if File_servicios_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_servicios_proto_rawDesc), len(file_servicios_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_servicios_proto_goTypes,
		DependencyIndexes: file_servicios_proto_depIdxs,
		MessageInfos:      file_servicios_proto_msgTypes,
	}.Build()
	File_servicios_proto = out.File
	file_servicios_proto_goTypes = nil
	file_servicios_proto_depIdxs = nil
}
